# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetPostTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.5'
	pod 'SwiftyJSON'

  # Pods for GetPostTest

  target 'GetPostTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GetPostTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
